### ISSUE TITLE
A Skeleton project fails on building with embedded Monaco Editor

### ISSUE THREAD

**Issue by dumtux** [Brain-Bones/skeleton#574]
### Current Behavior

I placed a JS code editor using [Monaco Editor](https://github.com/microsoft/monaco-editor) on a page.

![Screenshot from 2022-11-18 09-03-04](https://user-images.githubusercontent.com/58913889/202592654-e1333a84-8de6-4ab6-8999-82c54e2bfaa8.png)

It runs well with no error or bug by using `npm run dev` command, which is an alias to `vite dev`.
However, I got an error forbuilding by using `npm run build` command, which is an alias to `vite build`.

```text
hotte@hotte-com:~/Workspace/johnsheedy/omega2-4g-gateway/webapp/towerpanel-frontend$ npm run build
......

✓ 234 modules transformed.
✓ 545 modules transformed.
[commonjs--resolver] Unexpected token (56:7) in /home/hotte/Workspace/johnsheedy/omega2-4g-gateway/webapp/towerpanel-frontend/node_modules/monaco-editor/esm/vs/basic-languages/perl/perl.js
file: /home/hotte/Workspace/johnsheedy/omega2-4g-gateway/webapp/towerpanel-frontend/node_modules/monaco-editor/esm/vs/basic-languages/perl/perl.js:56:7
54:     "ne",
55:     "sub",
56:     "__PACKAGE__",
           ^
57:     "for",
58:     "no",
error during build:
SyntaxError: Unexpected token (56:7) in /home/hotte/Workspace/johnsheedy/omega2-4g-gateway/webapp/towerpanel-frontend/node_modules/monaco-editor/esm/vs/basic-languages/perl/perl.js
    at pp$4.raise (file:///home/hotte/Workspace/johnsheedy/omega2-4g-gateway/webapp/towerpanel-frontend/node_modules/rollup/dist/es/shared/rollup.js:19420:13)
    at pp$9.unexpected (file:///home/hotte/Workspace/johnsheedy/omega2-4g-gateway/webapp/towerpanel-frontend/node_modules/rollup/dist/es/shared/rollup.js:16714:8)
    at pp$9.expect (file:///home/hotte/Workspace/johnsheedy/omega2-4g-gateway/webapp/towerpanel-frontend/node_modules/rollup/dist/es/shared/rollup.js:16708:26)
    at pp$5.parseExprList (file:///home/hotte/Workspace/johnsheedy/omega2-4g-gateway/webapp/towerpanel-frontend/node_modules/rollup/dist/es/shared/rollup.js:19287:12)
    at pp$5.parseExprAtom (file:///home/hotte/Workspace/johnsheedy/omega2-4g-gateway/webapp/towerpanel-frontend/node_modules/rollup/dist/es/shared/rollup.js:18766:26)
    at pp$5.parseExprSubscripts (file:///home/hotte/Workspace/johnsheedy/omega2-4g-gateway/webapp/towerpanel-frontend/node_modules/rollup/dist/es/shared/rollup.js:18587:19)
    at pp$5.parseMaybeUnary (file:///home/hotte/Workspace/johnsheedy/omega2-4g-gateway/webapp/towerpanel-frontend/node_modules/rollup/dist/es/shared/rollup.js:18553:17)
    at pp$5.parseExprOps (file:///home/hotte/Workspace/johnsheedy/omega2-4g-gateway/webapp/towerpanel-frontend/node_modules/rollup/dist/es/shared/rollup.js:18480:19)
    at pp$5.parseMaybeConditional (file:///home/hotte/Workspace/johnsheedy/omega2-4g-gateway/webapp/towerpanel-frontend/node_modules/rollup/dist/es/shared/rollup.js:18463:19)
    at pp$5.parseMaybeAssign (file:///home/hotte/Workspace/johnsheedy/omega2-4g-gateway/webapp/towerpanel-frontend/node_modules/rollup/dist/es/shared/rollup.js:18430:19)
hotte@hotte-com:~/Workspace/johnsheedy/omega2-4g-gateway/webapp/towerpanel-frontend$ 
```

### Steps To Reproduce

I published the source code here https://github.com/dumtux/towerpanel/tree/develop
(the project is not too big :smiley:  )
Thus I believe  this can reproduce the error.

```sh
git clone https://github.com/dumtux/towerpanel
cd towerpanel/towerpanel-frontend
git checkout develop
npm install
npm run build
```

The Monaco Editor is embedded on https://github.com/dumtux/towerpanel/blob/develop/towerpanel-frontend/src/lib/components/JSEditor/JSEditor.svelte

**Comment by endigo9740** [comment]
@dumtux did you mean to report this on the Skeleton repo? Nothing expressed above seems related to Skeleton. Seems you're running into bugs with Monaco. I might suggest reporting your issue on their project repo.

Currently the only code-related feature Skeleton supports is using Highlight.js with code blocks. The docs are here:
https://www.skeleton.dev/utilities/codeblocks

If this was submitting in error please go ahead and let me know so we can close out this ticket. Thanks!

**Comment by niktek** [comment]
Not manual running of `tsc`, have a look at the build script of the sample react setup https://github.com/microsoft/monaco-editor/blob/main/samples/browser-esm-vite-react/package.json, it calls `tsc` before `vite build`.   Which means it could be emitting extra typescript information needed for the build to succeed.  Likewise compare the tsconfig.json as well.

But again, try doing this in a bare Svelte Kit project to resolve the issues (reduces the number of moving parts your trying to deal with).  Skeleton is pure components that sit on top of Svelte-kit.  We don't do the bundling, transpiling, building etc.  Once you figure out how to get it working in a bare bones Svelte Kit project, then it will work when you add the Skeleton UI stuff on top.

**Comment by endigo9740** [comment]
@dumtux My point is that this is a Skeleton issue tracker. As stated above, nothing in the information provided ties this to Skeleton, and given the conversation with Nik it sounds like it's possibly a config or Vite issue. Plain and simple, is off topic and this issue tracker is not the appropriate place for this discussion.

I'd suggest the following:

- Reach out to the Monaco community for support with Monaco errors
- Consider trying our Discord. We have #svelte and #support channels which can sometimes get general support from other users and Skeleton contributors
- If you can determine there is an issue directly related to Skeleton, create a ticket here and let us know the specifics.

I'm not trying to be harsh here, but it sets a bad precedence if we provide support for issues outside the scope of Skeleton. Today it's you, tomorrow it's a handful of others, eventually we're not able to work on Skeleton because we've become a support company. Get what I mean?

Keep in mind that our contributors are volunteers devoting their free time. We are not general purpose support staff. I'm going to go ahead and close this out per the reasons explained in my message above.
